version: '3.9'
services:
  backend:
    build: ./userspet
    ports:
      - "8080:8080"
  frontend:
    build: ./users-with-pets-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
